create table public.users (
    id text not null,
    username text not null,
    email text not null,
    password text not null,
    bio text null default ''::text,
    preferences jsonb not null,
    food_restrictions jsonb null,
    latitude double precision null default '0'::double precision,
    longitude double precision null default '0'::double precision,
    notifications_enabled boolean null default true,
    created_at timestamp with time zone null default now(),
    modified_at timestamp with time zone null default now(),
    constraint users_pkey primary key (id),
    constraint users_email_key unique (email),
    constraint users_username_key unique (username)
) TABLESPACE pg_default;

create table public.friends (
    id text not null,
    user_id text not null,
    name text null,
    created_at timestamp with time zone not null default now(),
    modified_at timestamp with time zone not null default now(),
    constraint friends_pkey primary key (id),
    constraint friends_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.restaurants2 (
    id text not null,
    name text null,
    category text null,
    price text null,
    eta text null,
    rating double precision null,
    location text null,
    latitude double precision null default '0'::double precision,
    longitude double precision null default '0'::double precision,
    tags jsonb null default '[]'::jsonb,
    review_tag_profile jsonb null default '{}'::jsonb,
    vegan_level text null default 'UNKNOWN',
    vegetarian_level text null default 'UNKNOWN',
    halal_level text null default 'UNKNOWN',
    gluten_free_level text null default 'UNKNOWN',
    dairy_free_level text null default 'UNKNOWN',
    constraint restaurants2_pkey primary key (id)
) TABLESPACE pg_default;

create table public.restaurant_details (
    restaurant_id text not null,
    created_at timestamp with time zone not null default now(),
    name text not null,
    description text null default ''::text,
    rating bigint null default '0'::bigint,
    price_range text null,
    images jsonb null,
    attributes jsonb null,
    google_maps_link text null,
    restaurant_website text null,
    city text not null,
    address text null default ''::text,
    distance text null default ''::text,
    constraint restaurant_details_pkey primary key (restaurant_id),
    constraint restaurant_details_restaurant_id_fkey foreign KEY (restaurant_id) references restaurants2 (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.categories (
    id bigint generated by default as identity not null,
    label text not null,
    constraint categories_pkey primary key (id),
    constraint categories_label_key unique (label)
) TABLESPACE pg_default;

create table public.featured_items (
    id text not null,
    restaurant_id text not null,
    name text not null,
    price text not null,
    description text null default ''::text,
    created_at timestamp with time zone not null default now(),
    modified_at timestamp with time zone not null default now(),
    constraint featured_items_pkey primary key (id),
    constraint featured_items_restaurant_id_fkey foreign KEY (restaurant_id) references restaurants2 (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.popular_items (
    id bigint generated by default as identity not null,
    restaurant_id text null,
    title text not null,
    subtitle text not null,
    created_at timestamp with time zone not null default now(),
    modified_at timestamp with time zone not null default now(),
    constraint popular_items_pkey primary key (id),
    constraint popular_items_restaurant_id_fkey foreign KEY (restaurant_id) references restaurants2 (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.popular_items (
    id bigint generated by default as identity not null,
    restaurant_id text null,
    title text not null,
    subtitle text not null,
    created_at timestamp with time zone not null default now(),
    modified_at timestamp with time zone not null default now(),
    constraint popular_items_pkey primary key (id),
    constraint popular_items_restaurant_id_fkey foreign KEY (restaurant_id) references restaurants2 (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.user_saved_restaurants (
    user_id text not null,
    restaurant_id text not null,
    aved_at timestamp with time zone not null default now(),
    created_at timestamp with time zone not null default now(),
    modified_at timestamp with time zone not null default now(),
    constraint user_saved_restaurants_pkey primary key (user_id, restaurant_id),
    constraint user_saved_restaurants_restaurant_id_fkey foreign KEY (restaurant_id) references restaurants2 (id) on update CASCADE on delete CASCADE,
    constraint user_saved_restaurants_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.reviews (
    id text not null,
    restaurant_id text null,
    restaurant_name text not null,
    user_id text null,
    rating integer null default 0,
    content text null default ''::text,
    tags jsonb null default '[]'::jsonb,
    created_at timestamp with time zone null default now(),
    constraint reviews_pkey primary key (id),
    constraint reviews_restaurant_id_fkey foreign KEY (restaurant_id) references restaurants2 (id) on update CASCADE on delete SET null,
    constraint reviews_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete SET null
) TABLESPACE pg_default;

create table public.vote_sessions (
    id text not null,
    title text not null,
    created_at_epoch bigint not null,
    is_closed boolean not null default false,
    closed_at bigint null,
    created_at timestamp with time zone not null default now(),
    constraint vote_sessions_pkey primary key (id)
) TABLESPACE pg_default;

create table public.vote_session_participants (
    session_id text not null,
    user_id text not null,
    display_name text null,
    created_at timestamp with time zone not null default now(),
    constraint vote_session_participants_pkey primary key (session_id, user_id),
    constraint vote_session_participants_session_id_fkey foreign KEY (session_id) references vote_sessions (id) on update CASCADE on delete CASCADE,
    constraint vote_session_participants_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.vote_session_restaurants (
    session_id text not null,
    restaurant_id text not null,
    created_at timestamp with time zone not null default now(),
    constraint vote_session_restaurants_pkey primary key (session_id, restaurant_id),
    constraint vote_session_restaurants_session_id_fkey foreign KEY (session_id) references vote_sessions (id) on update CASCADE on delete CASCADE,
    constraint vote_session_restaurants_restaurant_id_fkey foreign KEY (restaurant_id) references restaurants2 (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.vote_session_votes (
    session_id text not null,
    user_id text not null,
    restaurant_id text not null,
    created_at timestamp with time zone not null default now(),
    constraint vote_session_votes_pkey primary key (session_id, user_id, restaurant_id),
    constraint vote_session_votes_session_id_fkey foreign KEY (session_id) references vote_sessions (id) on update CASCADE on delete CASCADE,
    constraint vote_session_votes_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete CASCADE,
    constraint vote_session_votes_restaurant_id_fkey foreign KEY (restaurant_id) references restaurants2 (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.friend_requests (
    id uuid not null default gen_random_uuid (),
    sender_id text not null,
    receiver_id text not null,
    status text not null default 'pending'::text,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint friend_requests_pkey primary key (id),
    constraint friend_requests_receiver_id_fkey foreign KEY (receiver_id) references users (id) on delete CASCADE,
    constraint friend_requests_sender_id_fkey foreign KEY (sender_id) references users (id) on delete CASCADE,
    constraint friend_requests_no_self_request_check check ((sender_id <> receiver_id)),
    constraint friend_requests_status_check check (
        (
            status = any (
                array[
                    'pending'::text,
                    'accepted'::text,
                    'rejected'::text
                ]
            )
        )
    )
) TABLESPACE pg_default;

create unique INDEX IF not exists friend_requests_one_pending_pair_idx on public.friend_requests using btree (
    LEAST(sender_id, receiver_id),
    GREATEST(sender_id, receiver_id)
    ) TABLESPACE pg_default
    where
    (status = 'pending'::text);
